//! Runnable tour: typed coded errors, profiling scopes, and the
//! deterministic fault report.
//!
//! ```sh
//! cargo run --example demo            # error path: prints the report
//! cargo run --example demo -- Cargo.toml   # happy path: logs a line
//! ```

#![feature(error_generic_member_access)] // error! emits Error::provide

use fast_observe::prelude::*;

error! {
    /// Errors the demo binary can fail with.
    pub enum DemoError {
        /// check the config path exists and is readable
        #[error("config unreadable: {path}")]
        #[code = "E100", category = Content]
        ConfigUnreadable {
            /// The path we tried to read.
            path: String,
        },
        /// The underlying I/O failure.
        #[error("io: {0}")]
        #[code = "E101", category = Transient, advice = "retry; if persistent, check the disk"]
        #[from]
        Io(std::io::Error),
    }
}

fn load_config(path: &str) -> Result<String, DemoError> {
    let _span = scope!("demo.load_config");
    // `ensure!` bails with the typed variant; `From<Variant> for
    // Fault<DemoError>` is generated by `error!`.
    ensure!(
        !path.is_empty(),
        ConfigUnreadable {
            path: path.to_owned()
        }
    );
    // `#[from]` wires io::Error → DemoError; `?` then lifts it into the fault.
    std::fs::read_to_string(path)
        .map_err(DemoError::from)
        .map_err(|e| Fault::from(e).attach_key("path", path.to_owned()))
}

fn main() {
    init(); // zero-config: stdout logs + fastrace console reporter

    let path = std::env::args().nth(1).unwrap_or_default();
    let _span = scope!("demo.main");

    match load_config(&path) {
        Ok(contents) => log::info!(bytes = contents.len(); "config loaded"),
        Err(fault) => {
            // The deterministic report: one fact per line.
            print!("{}", render_report(&fault));
            // The registry lookup behind the report's `hint:` line.
            if let Some(entry) = doctor("E100") {
                println!("\ndoctor E100:\n{entry}");
            }
            // What has failed in this process, and how often.
            println!("\nerror counts: {:?}", error_counts());
        }
    }
}
